# -*- coding: utf-8 -*-
"""image_stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rzj_6ZsmOiznRr7KHMihp5lLuJw9Dot3
"""

import numpy as np

def get_all_stats_by_line(image):
  indices = [i for i, _ in enumerate(image)]
  median = get_median_by_line(image)
  average = get_average_by_line(image)
  mean = get_mean_by_line(image)
  std = get_std_by_line(image)
  var = get_var_by_line(image)
  sum_line = get_sum_by_line(image)

  return indices, median, average, mean, std, var, sum_line

def get_stats_by_line_dict(image):
  indices = [i for i, _ in enumerate(image)]
  median = get_median_by_line(image)
  average = get_average_by_line(image)
  mean = get_mean_by_line(image)
  std = get_std_by_line(image)
  var = get_var_by_line(image)
  sum_line = get_sum_by_line(image)

  return {
      "median": median,
      "average": average,
      "mean": mean,
      "std": std,
      }

def get_all_stats(image):
  total_median = get_median(image)
  total_average = get_average(image)
  total_mean = get_mean(image)
  total_std = get_std(image)
  total_var = get_var(image)

  return total_median, total_average, total_mean, total_std, total_var

def get_median(image):
  return np.median(image)

def get_median_by_line(image):
  return [np.median(i) for i in image]

def get_average(image):
  return np.average(image)

def get_average_by_line(image):
  return [np.average(i) for i in image]

def get_mean(image):
  return np.mean(image)

def get_mean_by_line(image):
  return [np.mean(i) for i in image]

def get_std(image):
  return np.std(image)

def get_std_by_line(image):
  return [np.std(i) for i in image]

def get_var(image):
  return np.var(image)

def get_var_by_line(image):
  return [np.median(i) for i in image]

def get_sum_by_line(image):
  return [sum(i) for i in image]